version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:

      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo 'run your unit tests here'
  
  build:
    commands:

      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml --metadata mytable=geochat

      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json

artifacts:
  type: zip
  files:
    - template-export.yml
    - template-configuration.json
