AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  geochatddb:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: geochat
      AttributeDefinitions:
      - AttributeName: user
        AttributeType: S
      - AttributeName: timest
        AttributeType: S
      KeySchema:
      - AttributeName: user
        KeyType: HASH
      - AttributeName: timest
        KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
