AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  MyTable:
    Type: String
    Default: 'geochat'

Resources:

  frontend:
    Type: 'AWS::Serverless::Function'
    Properties:
      AutoPublishAlias: live
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1
      Events:
        PostHtml:
          Type: HttpApi
          Properties:
            Path: '/'
            Method: get
      Handler: frontend.handler
      Runtime: python3.8
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref MyTable
      CodeUri: lambda/frontend
      Description: 'Serve HTML traffic through API Gateway'
      MemorySize: 128
      Timeout: 3
      Tracing: Active
      ReservedConcurrentExecutions: 3
      Environment:
        Variables:
          dynamotable: !Ref MyTable

  backend:
    Type: 'AWS::Serverless::Function'
    Properties:
      AutoPublishAlias: live
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1
      Handler: backend.handler
      Runtime: python3.8
      Policies:
        - ComprehendReadOnly
        - DynamoDBCrudPolicy:
            TableName: !Ref MyTable
      CodeUri: lambda/backend
      Description: 'Run Comprehend on the message to detect sentiment and write the record into DynamoDB'
      MemorySize: 128
      Timeout: 10
      Tracing: Active
      ReservedConcurrentExecutions: 3
      Events:
        PostHtml:
          Type: HttpApi
          Properties:
            Path: '/'
            Method: post     
      Environment:
        Variables:
          dynamotable: !Ref MyTable
