AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  MyTable:
    Type: String
    Default: 'geochat'
  Stage:
    Type: String
    Description: The name for a project pipeline stage, such as Staging or Prod, for which resources are provisioned and deployed.
    Default: ''

Resources:
  frontend:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: frontend.handler
      Runtime: python3.8
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref MyTable
      CodeUri: lambda/frontend
      Description: 'Lambda function to serve HTML traffic through API Gateway'
      MemorySize: 512
      Timeout: 3
      Tracing: Active
      ReservedConcurrentExecutions: 3
      Events:
        GetHtml:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: get
      Environment:
        Variables:
          dynamotable: !Ref MyTable

  backend:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: backend.handler
      Runtime: python3.8
      Policies:
        - ComprehendReadOnly
        - DynamoDBCrudPolicy:
            TableName: !Ref MyTable
      CodeUri: lambda/backend
      Description: 'Lambda function receiving post messages which are written into DynamoDB'
      MemorySize: 512
      Timeout: 10
      Tracing: Active
      ReservedConcurrentExecutions: 3
      Events:
        PostHtml:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: post
      Environment:
        Variables:
          dynamotable: !Ref MyTable

Outputs:
  WebInterface:
    Value: { "Fn::Sub" : "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/home/"}
