AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
    MyTable:
        Type: String
	Default: geochat

Resources:
  html:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: python3.7
      Policies:
        - AmazonDynamoDBFullAccess
      CodeUri: ./lambda
      Description: 'Lambda function to serve HTML traffic through API Gateway'
      MemorySize: 128
      Timeout: 5
      Tracing: Active
      ReservedConcurrentExecutions: 10
      Events:
        GetHtml:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: get
      Environment:
        Variables:
          dynamotable: !Ref MyTable

Outputs:
  WebInterface:
    Value: { "Fn::Sub" : "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/home/"}

